bases:
- ../base

resources:
- namespace.yaml
- postgres-storage.yaml
- postgres.yaml
- backstage.yaml

configMapGenerator:
- name: app-config
  namespace: backstage
  files:
  - app-config.yaml

secretGenerator:
- name: postgres-secrets
  namespace: backstage
  literals:
  - POSTGRES_USER=admin
  - POSTGRES_PASSWORD=admin
