---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parodos-workflow-ingress
spec:
  rules:
  - host: workflow-service.parodos-dev
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: workflow-service
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parodos-notification-ingress
spec:
  rules:
  - host: notification-service.parodos-dev
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: notification-service
            port:
              number: 8080
